#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Eurovafliai — its own Google Cloud project"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create a dedicated Cloud project"
say "Eurovafliai currently borrows another app's Cloud project, so Google's"
say "sign-in screen says the wrong product name. A project of its own fixes"
say "that and keeps quotas and credentials separate."
open_url "https://console.cloud.google.com/projectcreate"
step "Project name: Eurovafliai"
step "Leave the organisation/location as offered, then click Create."
step "Wait for the notification, then select the new project."
note "The project ID is under the name — often eurovafliai-123456."
ask GOOGLE_CLOUD_PROJECT "Paste the project ID:"
PROJECT="$GOOGLE_CLOUD_PROJECT"
if [[ -z "$PROJECT" ]]; then
  warn "No project ID given; later links will open without a project selected."
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Name the app on the consent screen"
say "This is the name your friends read at sign-in: 'to continue to ...'."
open_url "https://console.cloud.google.com/auth/branding?project=${PROJECT}"
note "Older consoles call this APIs & Services → OAuth consent screen."
step "App name: Eurovafliai"
step "User support email: your own address."
step "Audience: External."
step "Developer contact information: your own address."
step "Save."
pause "Done? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Let the whole league sign in"
say "A new External app starts in Testing, where ONLY listed test users can"
say "sign in — everyone else gets 'access blocked'. Two ways out."
open_url "https://console.cloud.google.com/auth/audience?project=${PROJECT}"
step "Preferred: click Publish app, so any Google account can sign in."
note "Eurovafliai only asks for email and profile. Those are non-sensitive"
note "scopes, so publishing needs no Google verification review."
step "Alternative: stay in Testing and add each member under Test users."
warn "Testing mode caps you at 100 test users and expires tokens in 7 days."
pause "Published (or test users added)? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the OAuth client"
open_url "https://console.cloud.google.com/auth/clients?project=${PROJECT}"
note "Older consoles: APIs & Services → Credentials → Create credentials."
step "Create client → Application type: Web application."
step "Name: Eurovafliai web"
step "Under 'Authorised redirect URIs', add BOTH of these exactly:"
say  "    http://localhost:3007/auth/callback"
say  "    https://eurovafliai.labrium.online/auth/callback"
warn "localhost, NOT 127.0.0.1 — Google treats them as different URIs, and"
warn "the app builds its redirect from NEXT_PUBLIC_APP_URL (localhost:3007)."
step "Create, then copy the Client ID and the Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret (hidden):"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Teach PocketBase the new credentials"
say "PocketBase stores the provider config in its database, and the migration"
say "that sets it has already run — migrations run exactly once. So editing"
say ".env is not enough: the migration has to be reverted and re-applied."
if confirm "Revert and re-apply the Google OAuth2 migration now?"; then
  if pgrep -x pocketbase >/dev/null 2>&1; then
    warn "PocketBase is running. Stop it (Ctrl-C in its terminal) first."
    pause "Stopped? Press Enter."
  fi
  # `printf` rather than `yes`: under `set -o pipefail` a looping `yes` takes
  # SIGPIPE when PocketBase exits, and the non-zero status would abort the
  # wizard immediately after a successful revert. The migration's `down` reads
  # no environment, so .env does not need sourcing here — the re-apply happens
  # at the next PocketBase boot, where pb-serve.sh supplies it.
  if printf 'y\n' | ./pb/pocketbase migrate down 1 \
      --dir=pb/pb_data --migrationsDir=pb/pb_migrations; then
    say "Reverted. It re-applies from .env the next time PocketBase boots."
    say "Start the app with:  npm run dev"
  else
    warn "The revert failed — see the output above."
    SKIPPED+=("re-apply the OAuth2 migration by hand")
  fi
else
  SKIPPED+=("re-apply the OAuth2 migration: ./pb/pocketbase migrate down 1 --dir=pb/pb_data --migrationsDir=pb/pb_migrations, then npm run dev")
  note "Skipped — do it before testing, or PocketBase keeps the old client."
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Check it, then retire the old client"
say "With 'npm run dev' running, sign in and read the consent screen."
open_url "http://localhost:3007/login"
step "It should now say: to continue to Eurovafliai"
pause "Seeing the right name? Press Enter."
say "The old client in the shared project is now unused."
if confirm "Open the old project's clients page to delete it?"; then
  open_url "https://console.cloud.google.com/auth/clients?project=906508271779"
  warn "Delete ONLY the client named 'eurovafliai'. Leave the others alone —"
  warn "that project belongs to another app."
  pause "Done? Press Enter."
else
  note "Left in place. Harmless, just unused."
fi

finish
